version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.3
machine:
  environment:
    SHORT_GIT_HASH: $(echo $CIRCLE_SHA1 | cut -c -7)

jobs:
  build:
    docker:
      - image:  cimg/go:1.19

      - image: cimg/postgres:15.0
        environment: 
          - POSTGRES_USER=studententry
          - POSTGRES_PASSWORD=studententry
          - POSTGRES_DB=studententry

    

    steps:
      - checkout 

      - run:
          name: Initialize env variable
          command: | 
            echo "DBUsername=studententry
                DBHost=localhost
                DBPassword=studententry
                DBPort=5432
                DBName=studententry" > .env
      - run:
          name:  Wait for postgres
          command:  |
              for i in `seq 1 30`;
              do
                nc -z 127.0.0.1 3306 && echo Success && exit 0
                echo -n .
                sleep 1
              done
              echo Failed waiting MySQL && exit 1

      - run:
          name: FIrebase service account key
          command: | 
            echo $FIREBASE_SERVICE_KEY > FirebaseServiceKey.json
      
      - run:
          name: build go file
          command: | 
            go build main.go
      
      - run:
          name: Start Service
          command: ./main
          background: true
        
workflows:
  build-and-deploy:
    jobs:
      - build
      - gcp-gcr/build-and-push-image:
          requires:
            - build
          image: pensieve
          filters:
            branches:
              only:
                main